spring.application.name=subscriptions-java-spring
spring.datasource.url=${DB_URL}
# Database Credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL Driver (Optional: Spring Boot usually detects this automatically)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Schema Generation (use 'update' for development, 'none' for production)
spring.jpa.hibernate.ddl-auto=create-drop

# Optional: Show executed SQL in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
